services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 6500:5432
    env_file:
      - ./app.env
    volumes:
      - postgres:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - ./app.env
    ports:
      - 8080:80
    volumes:
      - pgadmin:/root/.pgadmin

volumes:
  postgres:
  pgadmin:
